[package]
name = "sample_multiple"
version = "0.1.0"
authors = ["Jonas Sicking <jonas@sicking.cc>"]

[dependencies]
rand = "0.5.*"

[[bin]]
name = "iter"
path = "src/time_iter.rs"

[[bin]]
name = "vec"
path = "src/time_vec.rs"
